### ISSUE TITLE
Add a loading "Mask" on page load to fix the "flashing" that happens due to JS display: none switches

### ISSUE THREAD

**Issue by thomasplevy** [gocodebox/lifterlms-lite-lms-progress-tracker#4]

**Comment by eri-trabiccolo** [comment]
something like in #22 
I used the llms spinner, it's not a true mask, you know because of the alpha, if we want the background to be solid then I think that we should allow customers to choose the background and the spinner color, and in this case, without outputting a custom style (in the head) we would need to add a spinner html element so that we can add inline style to it :(.
